spring:
  application:
    name: servicio-persona
  datasource:
    url: jdbc:mysql://localhost:3306/spring_test
    username: root
    password: damian
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

propertie.enviroment: propertiePROD